CREATE DATABASE CAR

CREATE TABLE PEOPLE(
PERSON_ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
)

CREATE TABLE CARS(
CAR_ID INT PRIMARY KEY,
MODEL VARCHAR(40) NOT NULL,
PERSON_ID INT NOT NULL FOREIGN KEY
REFERENCES PEOPLE(PERSON_ID)
)

ALTER TABLE CARS
ADD MARK VARCHAR(40) NOT NULL

INSERT INTO PEOPLE
VALUES
(1,'IVAN PETROV'),
(2,'IVA DRAGANOVA'),
(3,'MARIQ GENOVA'),
(4,'PETAR STOICHEV')

INSERT INTO CARS
VALUES
(1,'GOLF',1,'WOLKSWAGEG'),
(2,'DUSTER',2,'DACIA'),
(3,'SANDERO',3,'DACIA')


DELETE FROM CARS
WHERE CAR_ID=(SELECT TOP 1 CAR_ID FROM CARS ORDER BY CAR_ID DESC)


UPDATE  PEOPLE
SET NAME='HRISTO BOGDANOV'
WHERE PERSON_ID=4

SELECT P.NAME,C.MODEL
FROM PEOPLE P LEFT JOIN CARS C
ON C.PERSON_ID=P.PERSON_ID

SELECT P.NAME,COUNT(CAR_ID) AS TOTAL_CARS
FROM PEOPLE P JOIN CARS C
ON C.PERSON_ID=P.PERSON_ID
GROUP BY P.NAME