CREATE DATABASE [FirstDB]

USE [FirstDB]

CREATE TABLE STUDENTS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FNAME VARCHAR(50) NOT NULL,
	LNAME VARCHAR(50) NOT NULL,
	F_NUM VARCHAR(10)
)


INSERT INTO STUDENTS(FNAME,LNAME)
VALUES('Stefani', 'Paunova')

SELECT ID,FNAME
FROM STUDENTS

SELECT *
FROM STUDENTS

UPDATE STUDENTS
SET F_NUM='1701322001' 
WHERE ID=1

ALTER TABLE STUDENTS
ADD PHONE VARCHAR(10)

INSERT INTO STUDENTS(FNAME,LNAME,PHONE)
VALUES('Ivan', 'Ivanov', '0897654454')

DELETE FROM STUDENTS
WHERE ID=2

DROP TABLE STUDENTS