CREATE DATABASE Pizza

CREATE TABLE PIZZAS(
PIZZA_ID INT PRIMARY KEY,
PIZZA_TYPE VARCHAR(20) NOT NULL
)

CREATE TABLE CLIENTS(
CLIENT_ID INT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
PHONE VARCHAR(10) NOT NULL
)

CREATE TABLE PIZZA_ORDERS(
PIZZA_ID INT NOT NULL FOREIGN KEY
REFERENCES PIZZAS(PIZZA_ID),
CLIENT_ID INT NOT NULL FOREIGN KEY
REFERENCES CLIENTS(CLIENT_ID)
CONSTRAINT PK_PIZZAS_CLIENTS
PRIMARY KEY(PIZZA_ID,CLIENT_ID),
QUANTITY INT NOT NULL,
SIZE CHAR(1) NOT NULL,
DATETIME DATETIME NOT NULL
)


ALTER TABLE PIZZA_ORDERS 
ADD PRICE DECIMAL(5,2)
CHECK (PRICE>0)

ALTER TABLE CLIENTS
DROP COLUMN PHONE


INSERT INTO PIZZAS
VALUES (1,'Meatlovers'),
	   (2,'Margarita')

INSERT INTO CLIENTS
VALUES (1,'Ivan Ivanov'),
	   (2,'Petar Cvetkov')

INSERT INTO PIZZA_ORDERS
VALUES (1,1,2,'L','2022-5-5',12.56),
		(1,2,5,'S','2021-1-8',42.12),
		(2,1,7,'M','2022-12-12',51.10),
		(2,2,4,'L','2022-3-2',17.99)


UPDATE PIZZA_ORDERS
SET QUANTITY=5, SIZE='S'
WHERE PIZZA_ID=1


DELETE FROM PIZZA_ORDERS
WHERE PIZZA_ID=2


DELETE FROM PIZZAS
WHERE PIZZA_ID=2

SELECT C.NAME,PO.DATETIME,PO.SIZE
FROM CLIENTS C JOIN PIZZA_ORDERS PO
ON PO.CLIENT_ID=C.CLIENT_ID
WHERE PO.SIZE='S'
ORDER BY C.NAME DESC

INSERT INTO CLIENTS
VALUES (3,'Ivana Draganova')


SELECT C.NAME,COUNT(PO.CLIENT_ID) AS MADE_ORDERS
FROM CLIENTS C LEFT JOIN PIZZA_ORDERS PO
ON PO.CLIENT_ID=C.CLIENT_ID
GROUP BY C.NAME

SELECT P.PIZZA_TYPE, COUNT(PO.PIZZA_ID) AS ORDERS
FROM PIZZAS P JOIN PIZZA_ORDERS PO
ON PO.PIZZA_ID=P.PIZZA_ID
GROUP BY P.PIZZA_TYPE
HAVING COUNT(PO.PIZZA_ID)>1

CREATE VIEW V_PIZZA_SUM
AS
SELECT P.PIZZA_TYPE, SUM(PO.PRICE*PO.QUANTITY) AS SUM_PRICE
FROM PIZZAS P JOIN PIZZA_ORDERS PO
ON PO.PIZZA_ID=P.PIZZA_ID
GROUP BY P.PIZZA_TYPE
