USE PCTRADE

SELECT D.NAME AS DEPARTMENT, COUNT(E.EMPLOYEE_ID) AS [TOTAL EMPLOYEES]
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY D.NAME
ORDER BY 2 DESC
OFFSET 0 ROWS
FETCH NEXT 1 ROWS ONLY

SELECT C.CUSTOMER_ID, C.FNAME,C.LNAME, COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS C JOIN ORDERS O
ON O.CUSTOMER_ID=C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.FNAME,C.LNAME
HAVING COUNT(O.ORDER_ID)=1
ORDER BY C.FNAME ASC

SELECT J.JOB_TITLE, COUNT(E.EMPLOYEE_ID) AS [EMPLYEE COUNT]
FROM JOBS J LEFT JOIN EMPLOYEES E
ON E.JOB_ID=J.JOB_ID
GROUP BY J.JOB_TITLE
HAVING COUNT(E.EMPLOYEE_ID)=0


SELECT TOP 5 C.FNAME,C.LNAME,C.GENDER, O.ORDER_DATE
FROM CUSTOMERS C JOIN ORDERS O
ON O.CUSTOMER_ID=C.CUSTOMER_ID
ORDER BY O.ORDER_DATE DESC

